Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2024-08, with the labels that each got.

#7 [refactor] 패키지 구조를 변경합니다.
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/Recommendation.java
  back/src/main/java/org/pknu/weather/domain/Tag.java
  back/src/main/java/org/pknu/weather/domain/Weather.java
  back/src/main/java/org/pknu/weather/domain/common/RainType.java
  back/src/main/java/org/pknu/weather/domain/common/Sensitivity.java
  back/src/main/java/org/pknu/weather/domain/common/SkyType.java
Labels: :recycle: 리팩토링

#9 [refactor] 패키지 구조를 변경합니다.
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/Recommendation.java
  back/src/main/java/org/pknu/weather/domain/Tag.java
  back/src/main/java/org/pknu/weather/domain/Weather.java
  back/src/main/java/org/pknu/weather/domain/common/RainType.java
  back/src/main/java/org/pknu/weather/domain/common/Sensitivity.java
  back/src/main/java/org/pknu/weather/domain/common/SkyType.java
Labels: :recycle: 리팩토링

#32 [BE] health check 설정 추가
  back/build.gradle
  back/src/main/resources/application.yml
Labels: 설정, 기능

#38 [BE] CI 가 안되는 현상 해결중
  .github/workflows/gradle.yml
  back/Dockerfile
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/WeatherApplicationTests.java
  back/src/test/java/org/pknu/weather/common/WeatherFeignClientTest.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
  back/src/test/resources/application.yml
  test_back/.gitignore
  test_back/README.md
  test_back/build.gradle
  test_back/gradle/wrapper/gradle-wrapper.jar
  test_back/gradle/wrapper/gradle-wrapper.properties
  test_back/gradlew
  test_back/gradlew.bat
  test_back/settings.gradle
  test_back/src/main/java/com/weather/demo/DemoApplication.java
  test_back/src/main/java/com/weather/demo/TestController.java
  test_back/src/main/resources/application.yml
  test_back/src/test/java/com/weather/demo/DemoApplicationTests.java
Labels: 고치지 못했음

#40 [fix] Could not open JPA EntityManager for transaction 해결중
  .github/workflows/gradle.yml
  back/build.gradle
  back/src/main/java/org/pknu/weather/repository/WeatherRepository.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: :lady_beetle: 버그, 고치지 못했음

#47 [BE] 날씨 공유(post) 로직 작성 및 API 구현
  back/src/main/java/org/pknu/weather/apiPayload/ApiResponse.java
  back/src/main/java/org/pknu/weather/common/WeatherRangeConverter.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/Tag.java
  back/src/main/java/org/pknu/weather/domain/common/TemperatureRange.java
  back/src/main/java/org/pknu/weather/domain/tag/DustTag.java
  back/src/main/java/org/pknu/weather/domain/tag/EnumTag.java
  back/src/main/java/org/pknu/weather/domain/tag/HumidityTag.java
  back/src/main/java/org/pknu/weather/domain/tag/RainTag.java
  back/src/main/java/org/pknu/weather/domain/tag/SkyTag.java
  back/src/main/java/org/pknu/weather/domain/tag/TemperatureTag.java
  back/src/main/java/org/pknu/weather/domain/tag/WindTag.java
  back/src/main/java/org/pknu/weather/dto/PostRequest.java
  back/src/main/java/org/pknu/weather/dto/converter/PostConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/PostRequestConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/RecommendationConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/TagConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/PostRepository.java
  back/src/main/java/org/pknu/weather/repository/RecommendationRepository.java
  back/src/main/java/org/pknu/weather/repository/TagRepository.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: 백엔드, 기능

#56 [BE] 위경도 <-> 좌표 변환 유틸 클래스 수정
  back/src/main/java/org/pknu/weather/common/CoordinateConversionUtils.java
  back/src/main/java/org/pknu/weather/common/GeometryUtils.java
  back/src/main/java/org/pknu/weather/common/WeatherFeignClient.java
  back/src/test/java/org/pknu/weather/common/CoordinateConversionUtilsTest.java
Labels: :recycle: 리팩토링

#58 QueryDsl 설정
  back/build.gradle
Labels: 설정

#60 [BE/Feat] Kakao oauth 어세스 토큰 및 앱 jwt 토큰 구현
  .github/workflows/gradle.yml
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/org.pknu.weather.main.iml
  .idea/modules/org.pknu.weather.test.iml
  LOG_PATH_IS_UNDEFINED/LOG_FILE_NAME_IS_UNDEFINED.log
  LOG_PATH_IS_UNDEFINED/err_log.log
  back/build.gradle
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/config/FilterConfig.java
  back/src/main/java/org/pknu/weather/filter/OauthTokenFilter.java
  back/src/main/java/org/pknu/weather/filter/RefreshTokenFilter.java
  back/src/main/java/org/pknu/weather/filter/TokenCheckFilter.java
  back/src/main/java/org/pknu/weather/filter/TokenGenerateFilter.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/security/dto/LoginMemberDTO.java
  back/src/main/java/org/pknu/weather/security/exception/TokenException.java
  back/src/main/java/org/pknu/weather/security/oauth/KaKaoLoginClient.java
  back/src/main/java/org/pknu/weather/security/oauth/KakaoUserResponse.java
  back/src/main/java/org/pknu/weather/security/util/JWTUtil.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: 백엔드, 기능

#62 [BE/Bug] 깃허브 액션 실행 용 커밋 - 수정사항 없음
  .github/workflows/gradle.yml
Labels: :lady_beetle: 버그, 백엔드

#64 [BE/Bug] 깃허브 액션 실행 용 PR - 수정사항 없음
  .github/workflows/gradle.yml
Labels: :lady_beetle: 버그, 백엔드

#68 [BE/Fix] 테스트 코드, 설정 파일, 워크플로 파일 수정
  .github/workflows/gradle.yml
  back/src/main/java/org/pknu/weather/common/WeatherRangeConverter.java
  back/src/main/java/org/pknu/weather/domain/Weather.java
  back/src/test/resources/application.yml
Labels: CI/CD, 백엔드, :recycle: 리팩토링

#71 [BE/Feat] 위경도를 입력 받아 Location 저장
  LOG_PATH_IS_UNDEFINED/LOG_FILE_NAME_IS_UNDEFINED.log
  LOG_PATH_IS_UNDEFINED/err_log.log
  back/LOG_PATH_IS_UNDEFINED/err_log.log
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/common/SgisLocationUtils.java
  back/src/main/java/org/pknu/weather/common/feignClient/SgisClient.java
  back/src/main/java/org/pknu/weather/common/feignClient/dto/LocationRequestDTO.java
  back/src/main/java/org/pknu/weather/common/feignClient/dto/SgisAccessTokenRequestDTO.java
  back/src/main/java/org/pknu/weather/common/feignClient/dto/SgisAccessTokenResponseDTO.java
  back/src/main/java/org/pknu/weather/common/feignClient/dto/SgisLocationResponseDTO.java
  back/src/main/java/org/pknu/weather/common/feignClient/dto/SgisLocationWithCoorResponseDTO.java
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
  back/src/main/java/org/pknu/weather/dto/CoorRequest.java
  back/src/main/java/org/pknu/weather/dto/LocationDTO.java
  back/src/main/java/org/pknu/weather/dto/converter/LocationConverter.java
  back/src/main/java/org/pknu/weather/repository/LocationRepository.java
  back/src/main/java/org/pknu/weather/service/LocationService.java
  back/src/test/java/org/pknu/weather/common/WeatherFeignClientTest.java
  back/src/test/java/org/pknu/weather/common/sgis/SgisFeignTest.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
  back/src/test/resources/application.yml
Labels: 백엔드, 기능

#73 [BE/Feat] 유저의 기본 주소 조회 API 및 지역 정보를 저장할 때 멤버의 기본 장소로 설정하도록 수정
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/common/TokenConverter.java
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/security/util/JWTUtil.java
  back/src/main/java/org/pknu/weather/service/LocationService.java
Labels: 백엔드, 기능, :recycle: 리팩토링

#69 [BE/Feat] post 조회 api 구현
  .github/workflows/gradle.yml
  back/build.gradle
  back/src/main/java/org/pknu/weather/apiPayload/ApiResponse.java
  back/src/main/java/org/pknu/weather/apiPayload/code/status/SuccessStatus.java
  back/src/main/java/org/pknu/weather/common/GeometryUtils.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/dto/PostResponse.java
  back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherConverter.java
  back/src/main/java/org/pknu/weather/repository/LocationRepository.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/PostRepository.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/common/CoordinateConversionUtilsTest.java
  back/src/test/java/org/pknu/weather/common/DateTimeFormatUtilsTest.java
  back/src/test/java/org/pknu/weather/common/WeatherFeignClientTest.java
  back/src/test/java/org/pknu/weather/domain/LocationTest.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
  back/src/test/resources/application-action.yml
  back/src/test/resources/application.yml
Labels: 백엔드, 기능

#82 [BE/Feat] post를 조회할 때 좋아요 갯수와 조회를 하는 사용자가 좋아요를 누를 수 있는지 여부를 함께 반환합니다.
  back/src/main/java/org/pknu/weather/common/DateTimeFormaterUtils.java
  back/src/main/java/org/pknu/weather/common/RecommendationUtils.java
  back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/Recommendation.java
  back/src/main/java/org/pknu/weather/dto/PostResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/PostQueryService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
  back/src/test/resources/application-action.yml
  back/src/test/resources/application.yml
Labels: 백엔드, 기능

#85 [BE/Fix] post 조회시 생성 시각이 음수로 반환되는 현상 수정
  .github/workflows/gradle.yml
  back/src/main/java/org/pknu/weather/common/DateTimeFormaterUtils.java
Labels: :lady_beetle: 버그

#77 [BE/Bug]사용자의 어세스 토큰에서 이메일을 가져오도록 하는 스태틱 메서드 생성
  back/src/main/java/org/pknu/weather/common/ApplicationStartupListener.java
  back/src/main/java/org/pknu/weather/common/SgisLocationUtils.java
  back/src/main/java/org/pknu/weather/common/TokenConverter.java
  back/src/main/java/org/pknu/weather/common/feignClient/dto/SgisLocationResponseDTO.java
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
  back/src/main/java/org/pknu/weather/dto/LocationDTO.java
  back/src/main/java/org/pknu/weather/dto/converter/LocationConverter.java
  back/src/main/java/org/pknu/weather/service/LocationService.java
  back/src/main/resources/application.yml
Labels: :lady_beetle: 버그, 백엔드

#92 [BE/Fix] CI 테스트 및 빌드 과정에서 환경변수가 제대로 적용되지 않던 문제점 수정
  .github/workflows/gradle.yml
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
  back/src/test/resources/application.yml
Labels: 고치지 못했음
