Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2024-09, with the labels that each got.

#91 [BE/Refactor]common 폴더 분류 및 security 폴더 일부 수정
  back/src/main/java/org/pknu/weather/common/converter/TokenConverter.java
  back/src/main/java/org/pknu/weather/common/converter/WeatherRangeConverter.java
  back/src/main/java/org/pknu/weather/common/eventListener/ApplicationStartupListener.java
  back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java
  back/src/main/java/org/pknu/weather/common/utils/GeometryUtils.java
  back/src/main/java/org/pknu/weather/common/utils/RecommendationUtils.java
  back/src/main/java/org/pknu/weather/common/utils/SgisLocationUtils.java
  back/src/main/java/org/pknu/weather/config/FilterConfig.java
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
  back/src/main/java/org/pknu/weather/domain/BaseEntity.java
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/Recommendation.java
  back/src/main/java/org/pknu/weather/domain/Tag.java
  back/src/main/java/org/pknu/weather/domain/Weather.java
  back/src/main/java/org/pknu/weather/dto/converter/LocationConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherConverter.java
  back/src/main/java/org/pknu/weather/feignClient/KaKaoLoginClient.java
  back/src/main/java/org/pknu/weather/feignClient/SgisClient.java
  back/src/main/java/org/pknu/weather/feignClient/WeatherFeignClient.java
  back/src/main/java/org/pknu/weather/feignClient/dto/LocationRequestDTO.java
  back/src/main/java/org/pknu/weather/feignClient/dto/SgisAccessTokenRequestDTO.java
  back/src/main/java/org/pknu/weather/feignClient/dto/SgisAccessTokenResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/dto/SgisLocationResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/dto/SgisLocationWithCoorResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/utils/WeatherApiUtils.java
  back/src/main/java/org/pknu/weather/filter/OauthTokenFilter.java
  back/src/main/java/org/pknu/weather/security/dto/KakaoUserResponseDTO.java
  back/src/main/java/org/pknu/weather/service/LocationService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/test/java/org/pknu/weather/common/DateTimeFormatUtilsTest.java
  back/src/test/java/org/pknu/weather/common/WeatherFeignClientTest.java
  back/src/test/java/org/pknu/weather/common/sgis/SgisFeignTest.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: 백엔드, :recycle: 리팩토링

#98 [BE/Fix] 클래스 명칭 변경 및 일부 수정
  back/src/main/java/org/pknu/weather/common/WeatherParamsFactory.java
  back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java
  back/src/main/java/org/pknu/weather/common/utils/GeometryUtils.java
  back/src/main/java/org/pknu/weather/domain/Tag.java
  back/src/main/java/org/pknu/weather/dto/TagResponse.java
  back/src/main/java/org/pknu/weather/feignClient/WeatherFeignClient.java
  back/src/main/java/org/pknu/weather/feignClient/dto/PointDTO.java
  back/src/main/java/org/pknu/weather/repository/TagRepository.java
  back/src/main/resources/application-prod.yml
  back/src/test/java/org/pknu/weather/common/DateTimeFormatUtilsTest.java
  back/src/test/java/org/pknu/weather/common/DateTimeFormatterTest.java
Labels: 백엔드, :recycle: 리팩토링

#100 [BE/Feat] 지역에서 좋아요를 가장 많이 받은 게시글 조회 API
  back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/dto/PostResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/PostQueryService.java
  back/src/test/java/org/pknu/weather/common/DateTimeFormatterTest.java
  back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: 백엔드, 기능

#102 [BE/Feat] 게시글 좋아요 기능 API
  back/src/main/java/org/pknu/weather/apiPayload/ApiResponse.java
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/repository/PostRepository.java
  back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/RecommendationRepository.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/java/org/pknu/weather/validation/annotation/IsPositive.java
  back/src/main/java/org/pknu/weather/validation/validator/PostExistValidator.java
Labels: 백엔드, 기능

#111 [BE/Feat] 멤버 정보 수정 및 S3적용
  .github/workflows/gradle.yml
  back/build.gradle
  back/src/main/java/org/pknu/weather/common/utils/LocalUploaderUtils.java
  back/src/main/java/org/pknu/weather/common/utils/S3UploaderUtils.java
  back/src/main/java/org/pknu/weather/config/S3Config.java
  back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/dto/MemberJoinDTO.java
  back/src/main/java/org/pknu/weather/dto/MemberRequest.java
  back/src/main/java/org/pknu/weather/dto/MemberResponseDTO.java
  back/src/main/java/org/pknu/weather/dto/converter/MemberResponseConverter.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/common/DateTimeFormatterTest.java
  back/src/test/java/org/pknu/weather/common/S3ImageUploadTest.java
  back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
  back/src/test/resources/application.yml
  back/src/test/resources/logback-test.xml
Labels: 백엔드, 기능

#112 [BE/Fix] 검증 값 수정
  back/src/main/java/org/pknu/weather/dto/PostRequest.java
Labels: 백엔드, :recycle: 리팩토링

#121 [BE/Fix]Member 정보 변경 시, null 값 확인 후 멤버 저장
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
Labels: :lady_beetle: 버그, 백엔드

#128 [BE/Feat] 날씨 정보 조회 API 호출시 날씨 정보 생성 및 갱신에 대한 로직 추가
  back/build.gradle
  back/src/main/java/org/pknu/weather/WeatherApplication.java
  back/src/main/java/org/pknu/weather/apiPayload/ApiResponse.java
  back/src/main/java/org/pknu/weather/apiPayload/code/status/SuccessStatus.java
  back/src/main/java/org/pknu/weather/common/GlobalParams.java
  back/src/main/java/org/pknu/weather/common/aspect/MainPageControllerAspect.java
  back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java
  back/src/main/java/org/pknu/weather/config/AsyncConfig.java
  back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Weather.java
  back/src/main/java/org/pknu/weather/dto/PostRequest.java
  back/src/main/java/org/pknu/weather/feignClient/WeatherFeignClient.java
  back/src/main/java/org/pknu/weather/feignClient/utils/WeatherApiUtils.java
  back/src/main/java/org/pknu/weather/repository/LocationCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/LocationCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/WeatherRepository.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/MemberQueryService.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
  back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/test/java/org/pknu/weather/common/DateTimeFormatterTest.java
  back/src/test/java/org/pknu/weather/common/TestGlobalParams.java
  back/src/test/java/org/pknu/weather/repository/TagRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: 백엔드, 기능

#135 [BE/Feat] 간단 날씨 정보 - 강수 정보 조회 API 구현
  back/src/main/java/org/pknu/weather/common/GlobalParams.java
  back/src/main/java/org/pknu/weather/common/utils/QueryUtils.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/dto/WeatherQueryResult.java
  back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/LocationCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/LocationCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
Labels: 백엔드, 기능
