Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2024-11, with the labels that each got.

#183 [BE/FIX] : 사용자의 기본 주소 설정 응답 값 location id 추가 및 기본 지역 생성 API 추가
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
  back/src/main/java/org/pknu/weather/service/LocationService.java
Labels: :lady_beetle: 버그, 백엔드

#188 [BE/Feat] 체감 온도 추가 및 일부 코드 수정
  back/src/main/java/org/pknu/weather/aop/BusinessLogicLoggingAspect.java
  back/src/main/java/org/pknu/weather/common/utils/SensibleTemperatureUtils.java
  back/src/main/java/org/pknu/weather/config/AsyncConfig.java
  back/src/main/java/org/pknu/weather/domain/Weather.java
  back/src/main/java/org/pknu/weather/domain/tag/RainTag.java
  back/src/main/java/org/pknu/weather/dto/WeatherQueryResult.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/test/java/org/pknu/weather/aop/AspectTest.java
  back/src/test/java/org/pknu/weather/domain/WeatherTest.java
  back/src/test/java/org/pknu/weather/dto/converter/WeatherResponseConverterTest.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/resources/application.yml
Labels: 백엔드, 기능, :recycle: 리팩토링

#199 [BE/Feat] 로케이션 Id를 통해 원하는 지역의 날씨 정보를 얻을 수 있도록 수정
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/domain/ExtraWeather.java
  back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
  back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
Labels: 백엔드, 기능

#202 [BE/Fix] AOP 포인트컷 수정
  back/src/main/java/org/pknu/weather/aop/LocationCheckAspect.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
Labels: :lady_beetle: 버그

#209 [BE/Feat]주소 검색 api 리팩토링
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
Labels: 백엔드, :recycle: 리팩토링

#222 [BE/Config] 모니터링 툴 구축을 위한 라이브러리와 설정 추가
  back/build.gradle
  back/src/main/resources/application.yml
Labels: 백엔드, 설정
