Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2024-10, with the labels that each got.

#144 [BE/Feat] 스프링 AOP 관련 코드 추가 및 수정
  back/src/main/java/org/pknu/weather/aop/BusinessLogicLoggingAspect.java
  back/src/main/java/org/pknu/weather/aop/ExecuteTimeAspect.java
  back/src/main/java/org/pknu/weather/aop/LocationCheckAspect.java
  back/src/main/java/org/pknu/weather/aop/Pointcuts.java
  back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/test/java/org/pknu/weather/aop/AspectTest.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
  back/src/test/java/org/pknu/weather/common/TestGlobalParams.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/MainPageServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: 백엔드, 기능

#147 [BE/Fix] /api/v1/main/weather 응답값 일부 수정
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
Labels: 기능, :recycle: 리팩토링

#145 Feat#118
  .github/workflows/gradle.yml
  back/build.gradle
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/common/converter/CoordinateConverter.java
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
  back/src/main/java/org/pknu/weather/domain/ExtraWeather.java
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/dto/MemberResponse.java
  back/src/main/java/org/pknu/weather/dto/MemberResponseDTO.java
  back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/MemberResponseConverter.java
  back/src/main/java/org/pknu/weather/feignClient/AirConditionClient.java
  back/src/main/java/org/pknu/weather/feignClient/UVClient.java
  back/src/main/java/org/pknu/weather/feignClient/dto/AirConditionResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/dto/AirObservatoryResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/dto/UVResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
  back/src/main/java/org/pknu/weather/repository/ExtraWeatherRepository.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/common/feignClient/AirConditionFeignTest.java
  back/src/test/java/org/pknu/weather/common/feignClient/SgisFeignTest.java
  back/src/test/java/org/pknu/weather/common/feignClient/UVFeignTest.java
  back/src/test/java/org/pknu/weather/repository/LocationCodeRepositoryTest.java
  back/src/test/resources/application.yml
Labels: 백엔드, 기능

#149 [BE/Fix] postType 추가
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/common/PostType.java
Labels: 백엔드, 설계

#153 [FE/Fix] 대표 주소 설정 로직 수정
  front/App.js
  front/src/api/api.js
  front/src/components/CurrentLocation.js
  front/src/components/InterestItem.js
  front/src/components/InterestPostScroll.js
  front/src/screens/InterestPostCreationScreen.js
  front/src/screens/InterestScreen.js
  front/src/screens/LoginScreen.js
  front/src/screens/MyScreen.js
  front/src/screens/RegisterProfileScreen.js
Labels: 프론트, 기능

#158 [BE/Refactor] 간단 날씨 보기 API 들의 응답값 수정
  back/src/main/java/org/pknu/weather/common/utils/TagUtils.java
  back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
Labels: 백엔드, :recycle: 리팩토링

#163 [BE/Refactor] 취미탭 글 쓰기, 조회하기 API 구현
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/common/PostType.java
  back/src/main/java/org/pknu/weather/domain/tag/SkyTag.java
  back/src/main/java/org/pknu/weather/dto/PostRequest.java
  back/src/main/java/org/pknu/weather/dto/converter/PostConverter.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/PostQueryService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/test/java/org/pknu/weather/common/Dummy.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
  back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: 백엔드, 기능, :recycle: 리팩토링

#168 [BE/Feat] 주소 검색 API 구현
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/common/utils/AddressFinder.java
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
  back/src/main/java/org/pknu/weather/service/LocationService.java
  back/src/test/java/org/pknu/weather/repository/LocationCodeRepositoryTest.java
Labels: 백엔드, 기능

#169 [BE/Fix]테스트 주석 처리
  back/src/test/java/org/pknu/weather/repository/LocationCodeRepositoryTest.java
Labels: :lady_beetle: 버그, 백엔드

#172 [BE/FEAT] 주소 생성 API 작성
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/common/utils/SgisLocationUtils.java
  back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
  back/src/main/java/org/pknu/weather/service/LocationService.java
Labels: 백엔드, 기능
