Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2025-04, with the labels that each got.

#393 [BE] 개발 서버 로그를 스레드 단위로 기록하도록 수정합니다
  back/src/main/java/org/pknu/weather/aop/Pointcuts.java
  back/src/main/java/org/pknu/weather/aop/util/LoggingUtils.java
Labels: :recycle: 리팩토링

#391 [BE] 레벨시스템 일부 구현
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/config/ExpRewardPolicyConfig.java
  back/src/main/java/org/pknu/weather/controller/MemberControllerV2.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/exp/CreatePostExpRewardLimitPolicy.java
  back/src/main/java/org/pknu/weather/domain/exp/ExpEvent.java
  back/src/main/java/org/pknu/weather/domain/exp/ExpRewardLimitPolicy.java
  back/src/main/java/org/pknu/weather/domain/exp/Level.java
  back/src/main/java/org/pknu/weather/domain/exp/RecommendationExpRewardLimitPolicy.java
  back/src/main/java/org/pknu/weather/dto/ExpRewardResponseDTO.java
  back/src/main/java/org/pknu/weather/dto/MemberResponse.java
  back/src/main/java/org/pknu/weather/dto/PostResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/ExpRewardResponseConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/MemberResponseConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/ExpRewardService.java
  back/src/main/java/org/pknu/weather/service/PostQueryService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/test/java/org/pknu/weather/common/Dummy.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
  back/src/test/java/org/pknu/weather/controller/CommunityControllerV1Test.java
  back/src/test/java/org/pknu/weather/controller/MemberControllerV1Test.java
  back/src/test/java/org/pknu/weather/controller/MemberControllerV2Test.java
  back/src/test/java/org/pknu/weather/controller/PostControllerV1Test.java
  back/src/test/java/org/pknu/weather/domain/exp/CreatePostExpRewardLimitPolicyTest.java
  back/src/test/java/org/pknu/weather/domain/exp/LevelTest.java
  back/src/test/java/org/pknu/weather/domain/exp/RecommendationExpRewardLimitPolicyTest.java
  back/src/test/java/org/pknu/weather/repository/MemberRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/ExpRewardServiceTest.java
  back/src/test/java/org/pknu/weather/service/MemberServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: 백엔드, 기능

#395 [BE/Refactor] 예보 API 에러로 인한 재시도 코드 작성
  back/build.gradle
  back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java
  back/src/main/java/org/pknu/weather/config/RetryConfig.java
  back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
  back/src/main/java/org/pknu/weather/feignClient/utils/WeatherFeignClientUtils.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/test/java/org/pknu/weather/common/formatter/DateTimeFormatterTest.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
Labels: :recycle: 리팩토링

#397 [BE/Fix] 커넥션 누수 지점 찾는 중
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/java/org/pknu/weather/service/WeatherWriteService.java
  back/src/main/resources/application.yml
Labels: :recycle: 리팩토링

#398 [BE/Fix] 커넥션 누수 개선
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/Tag.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/java/org/pknu/weather/service/WeatherWriteService.java
  back/src/main/resources/application.yml
Labels: :lady_beetle: 버그

#399 [FE/Feat] FCM 토큰 변경 감지 기능 구현
  front/android/app/src/main/AndroidManifest.xml
  front/android/app/src/main/res/values/colors.xml
Labels: 프론트, 기능

#404 [BE/Feat] 레벨 시스템 추가 개발
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/common/utils/RecommendationUtils.java
  back/src/main/java/org/pknu/weather/config/AsyncConfig.java
  back/src/main/java/org/pknu/weather/controller/AttendanceControllerV1.java
  back/src/main/java/org/pknu/weather/controller/ExpRewardControllerV1.java
  back/src/main/java/org/pknu/weather/controller/MemberControllerV2.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Attendance.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/Recommendation.java
  back/src/main/java/org/pknu/weather/domain/exp/CreatePostExpRewardLimitPolicy.java
  back/src/main/java/org/pknu/weather/domain/exp/ExpEvent.java
  back/src/main/java/org/pknu/weather/dto/ExpEventRequestDto.java
  back/src/main/java/org/pknu/weather/dto/ExpEventResponseDto.java
  back/src/main/java/org/pknu/weather/dto/converter/ExpEventResponseConverter.java
  back/src/main/java/org/pknu/weather/exception/ExceptionAdvice.java
  back/src/main/java/org/pknu/weather/repository/AttendanceRepository.java
  back/src/main/java/org/pknu/weather/repository/MemberCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/MemberCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/RecommendationRepository.java
  back/src/main/java/org/pknu/weather/service/AttendanceService.java
  back/src/main/java/org/pknu/weather/service/ExpRewardService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/java/org/pknu/weather/service/RecommendationService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/test/java/org/pknu/weather/common/Test.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
  back/src/test/java/org/pknu/weather/controller/MainPageControllerV1Test.java
  back/src/test/java/org/pknu/weather/controller/MemberControllerV1Test.java
  back/src/test/java/org/pknu/weather/controller/MemberControllerV2Test.java
  back/src/test/java/org/pknu/weather/domain/exp/CreatePostExpRewardLimitPolicyTest.java
  back/src/test/java/org/pknu/weather/repository/MemberRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/RecommendationRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/ExpRewardServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceUnitTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: 기능, :recycle: 리팩토링
