Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2025-02, with the labels that each got.

#297 [BE/Fix] 빈 게시글 조회 안되도록 수정
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/repository/PostCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/WeatherQueryServiceTest.java
  back/src/test/resources/application.yml
Labels: 백엔드, 수정

#302 [BE/Fix] 일부 api 버그 수정
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/TagCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/PostQueryService.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
  back/src/test/java/org/pknu/weather/common/TestUtil.java
  back/src/test/java/org/pknu/weather/controller/MemberControllerV1Test.java
  back/src/test/java/org/pknu/weather/repository/PostCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: :lady_beetle: 버그

#307 [BE/Ci] ci 실행 조건 수정
  .github/workflows/gradle-dev.yml
  .github/workflows/gradle-prod.yml
  .github/workflows/gradle-test.yml
Labels: CI/CD

#309 [BE/Ci] 환경변수가 적용 안되는 문제 해결
  .github/workflows/gradle-dev.yml
  .github/workflows/gradle-test.yml
Labels: CI/CD

#313 [BE/Ci] 개발서버 배포 워크플로 적용이 안돼서 수정
  .github/workflows/gradle-dev.yml
  .github/workflows/gradle-test.yml
Labels: CI/CD

#315 [BE/Ci] ci/cd 워크플로 파일 수정
  .github/workflows/gradle-dev-cd.yml
  .github/workflows/gradle-dev-ci.yml
Labels: CI/CD

#329 [FE/Fix] 위치 접근 권한 안내 수정
  front/android/app/build.gradle
  front/android/app/src/main/AndroidManifest.xml
  front/android/app/src/main/res/values/strings.xml
  front/ios/Weather2.xcodeproj/project.pbxproj
  front/ios/Weather2/Info.plist
  front/src/components/WeatherHeader.js
  front/src/screens/LoginScreen.js
  front/src/screens/RegisterProfileScreen.js
Labels: :recycle: 리팩토링

#341 [BE/Refactor] 일부 메서드 성능 개선 및 로직 수정
  back/build.gradle
  back/src/main/java/org/pknu/weather/WeatherApplication.java
  back/src/main/java/org/pknu/weather/aop/LocationCheckAspect.java
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/repository/TagCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/WeatherRepository.java
  back/src/main/java/org/pknu/weather/service/MemberQueryService.java
  back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/WeatherQueryServiceTest.java
Labels: :recycle: 리팩토링
