Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2025-03, with the labels that each got.

#343 [FE/Fix] UI 깨짐 방지 및 그래프 개선
  front/android/app/src/main/AndroidManifest.xml
  front/ios/Weather2/Info.plist
  front/src/components/WeatherGraph.js
  front/src/screens/LoginScreen.js
Labels: :lady_beetle: 버그, :recycle: 리팩토링

#346 Feat#344
  back/src/main/java/org/pknu/weather/domain/ExtraWeather.java
  back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
  back/src/main/java/org/pknu/weather/dto/converter/ExtraWeatherConverter.java
  back/src/main/java/org/pknu/weather/feignClient/dto/AirConditionResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
Labels: 백엔드, :recycle: 리팩토링, 수정

#349 bug: 미세 먼지 수치의 정상적인 숫자 값을 못 받은 경우 처리
  back/src/main/java/org/pknu/weather/feignClient/dto/AirConditionResponseDTO.java
  back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
Labels: :lady_beetle: 버그, 백엔드

#351 bug: 미세먼지 조회 시 지역이 제대로 설정되지 않는 문제 해결
  back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
Labels: :lady_beetle: 버그, 백엔드

#352 Release -> main
  back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
Labels: :lady_beetle: 버그, 백엔드

#353 Release -> dev
  back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java
  back/src/main/java/org/pknu/weather/feignClient/dto/WeatherParams.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/config/DataJpaTestConfig.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/MemberRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
Labels: 백엔드

#342 Release -> main
  back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java
  back/src/main/java/org/pknu/weather/feignClient/dto/WeatherParams.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/config/DataJpaTestConfig.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/MemberRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
Labels: 백엔드

#357 Release -> dev
  README.md
  back/src/main/java/org/pknu/weather/feignClient/WeatherFeignClient.java
  back/src/main/java/org/pknu/weather/feignClient/config/FeignClientConfig.java
  back/src/main/java/org/pknu/weather/feignClient/error/CommonErrorDecoder.java
  back/src/main/java/org/pknu/weather/feignClient/error/WeatherFeignErrorDecoder.java
  back/src/main/java/org/pknu/weather/security/exception/WeatherFeignClientException.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/feignClient/WeatherFeignClientTest.java
  back/src/test/resources/application.yml
Labels: :lady_beetle: 버그

#363 [BE] 날씨 생성, 갱신을 위한 비동기 메서드 분리 및 로직 수정
  back/src/main/java/org/pknu/weather/feignClient/utils/WeatherApiUtils.java
  back/src/main/java/org/pknu/weather/feignClient/utils/WeatherFeignClientUtils.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/java/org/pknu/weather/service/WeatherWriteService.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: :recycle: 리팩토링

#369 Release -> Main
  back/src/main/java/org/pknu/weather/domain/ExtraWeather.java
Labels: :lady_beetle: 버그, 백엔드

#371 [BE] 새로운 태그 조회 API 구현
  back/src/main/java/org/pknu/weather/common/mapper/EnumTagMapper.java
  back/src/main/java/org/pknu/weather/common/utils/TagUtils.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/controller/TagControllerV1.java
  back/src/main/java/org/pknu/weather/domain/tag/DustTag.java
  back/src/main/java/org/pknu/weather/domain/tag/EnumTag.java
  back/src/main/java/org/pknu/weather/domain/tag/HumidityTag.java
  back/src/main/java/org/pknu/weather/domain/tag/RainTag.java
  back/src/main/java/org/pknu/weather/domain/tag/SkyTag.java
  back/src/main/java/org/pknu/weather/domain/tag/TemperatureTag.java
  back/src/main/java/org/pknu/weather/domain/tag/WindTag.java
  back/src/main/java/org/pknu/weather/dto/TagSelectedOrNotDto.java
  back/src/main/java/org/pknu/weather/dto/TotalWeatherDto.java
  back/src/main/java/org/pknu/weather/dto/converter/TagConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/TagResponseConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/java/org/pknu/weather/service/TagQueryService.java
  back/src/test/java/org/pknu/weather/domain/EnumTagTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: 기능

#373 [BE/Fix] 예보 데이터가 제대로 갱신되지 않는 현상 수정
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
Labels: :lady_beetle: 버그

#375 Hotfix -> main
  back/src/main/java/org/pknu/weather/common/mapper/EnumTagMapper.java
  back/src/main/java/org/pknu/weather/common/utils/TagUtils.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/controller/TagControllerV1.java
  back/src/main/java/org/pknu/weather/domain/tag/DustTag.java
  back/src/main/java/org/pknu/weather/domain/tag/EnumTag.java
  back/src/main/java/org/pknu/weather/domain/tag/HumidityTag.java
  back/src/main/java/org/pknu/weather/domain/tag/RainTag.java
  back/src/main/java/org/pknu/weather/domain/tag/SkyTag.java
  back/src/main/java/org/pknu/weather/domain/tag/TemperatureTag.java
  back/src/main/java/org/pknu/weather/domain/tag/WindTag.java
  back/src/main/java/org/pknu/weather/dto/TagSelectedOrNotDto.java
  back/src/main/java/org/pknu/weather/dto/TotalWeatherDto.java
  back/src/main/java/org/pknu/weather/dto/converter/TagConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/TagResponseConverter.java
  back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/java/org/pknu/weather/service/TagQueryService.java
  back/src/main/java/org/pknu/weather/service/WeatherWriteService.java
  back/src/test/java/org/pknu/weather/domain/EnumTagTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: :lady_beetle: 버그

#370 Release -> Dev
  back/src/main/java/org/pknu/weather/domain/ExtraWeather.java
Labels: :lady_beetle: 버그, 백엔드

#381 Release -> Main
  front/App.js
  front/android/app/build.gradle
  front/android/app/google-services.json
  front/android/app/src/main/AndroidManifest.xml
  front/android/app/src/main/res/values/colors.xml
  front/android/build.gradle
  front/ios/GoogleService-Info.plist
  front/ios/Podfile
  front/ios/Podfile.lock
  front/ios/Weather2.xcodeproj/project.pbxproj
  front/ios/Weather2/AppDelegate.mm
  front/ios/Weather2/Info.plist
  front/ios/Weather2/PrivacyInfo.xcprivacy
  front/ios/Weather2/Weather2.entitlements
  front/package-lock.json
  front/package.json
  front/src/api/api.js
  front/src/components/AirQuality.js
  front/src/components/HourlyForecast.js
  front/src/components/WeatherGraph.js
  front/src/firebase/pushNotification.js
  front/src/hooks/usePushNotifications.js
  front/src/screens/LoginScreen.js
  front/src/screens/MyScreen.js
  front/src/screens/NotificationSettingScreen.js
  front/src/screens/TermsAgreementScreen.js
Labels: 프론트, 설정, 기능

#383 [BE/Refactor] 개발서버에서 예외처리된 예외는 세부 내용을 로깅하지 않도록 변경
  .github/workflows/gradle-dev-ci.yml
  back/src/main/java/org/pknu/weather/aop/util/LoggingUtils.java
Labels: 백엔드, 설정, :recycle: 리팩토링

#387 [BE/Refactor] NPE 예외 처리
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/WeatherWriteService.java
Labels: 백엔드, :recycle: 리팩토링
