Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2025-01, with the labels that each got.

#242 [BE/Refactor] #236
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/PostQueryService.java
  back/src/test/java/org/pknu/weather/config/TestConfig.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java
Labels: :recycle: 리팩토링

#247 [BE/Feat] 애플 로그인 및 회원탈퇴 추가
  .github/workflows/gradle.yml
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/config/AppConfig.java
  back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
  back/src/main/java/org/pknu/weather/feignClient/AppleAuthClient.java
  back/src/main/java/org/pknu/weather/feignClient/KaKaoAuthClient.java
  back/src/main/java/org/pknu/weather/filter/GenerateTokenFilter.java
  back/src/main/java/org/pknu/weather/security/dto/AppleAuthTokenResponse.java
  back/src/main/java/org/pknu/weather/security/dto/ApplePublicKey.java
  back/src/main/java/org/pknu/weather/security/dto/ApplePublicKeyResponse.java
  back/src/main/java/org/pknu/weather/security/util/AppTokenGenerator.java
  back/src/main/java/org/pknu/weather/security/util/ApplePublicKeyGenerator.java
  back/src/main/java/org/pknu/weather/security/util/JWTUtil.java
  back/src/main/java/org/pknu/weather/security/util/UserInfoStrategy.java
  back/src/main/java/org/pknu/weather/security/util/logout/AppleUnlinker.java
  back/src/main/java/org/pknu/weather/security/util/logout/KakaoUnlinker.java
  back/src/main/java/org/pknu/weather/security/util/logout/UserUnlinker.java
  back/src/main/java/org/pknu/weather/security/util/signup/AppleUserInfoStrategy.java
  back/src/main/java/org/pknu/weather/security/util/signup/KakaoUserInfoStrategy.java
  back/src/main/java/org/pknu/weather/security/util/signup/UserInfoStrategy.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/domain/TagTest.java
  back/src/test/java/org/pknu/weather/domain/WeatherTest.java
  back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
Labels: 백엔드, 기능

#251 [BE/FIX]: 회원 탈퇴 순서 변경 및 인증 정보 null 문제 해결
  back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
Labels: :lady_beetle: 버그, 백엔드

#260 [CI] cd 중복 step 제거
  .github/workflows/gradle.yml
Labels: CI/CD

#262 [BE/Fix] 버그 수정 중
  .github/workflows/gradle.yml
  back/src/main/java/org/pknu/weather/aop/BusinessLogicLoggingAspect.java
  back/src/main/java/org/pknu/weather/aop/ExecuteTimeAspect.java
  back/src/main/java/org/pknu/weather/aop/IntegrationLoggingAspect.java
  back/src/main/java/org/pknu/weather/aop/LocationCheckAspect.java
  back/src/main/java/org/pknu/weather/aop/Pointcuts.java
  back/src/main/java/org/pknu/weather/aop/util/ExecutionTimerUtils.java
  back/src/main/java/org/pknu/weather/aop/util/LoggingUtils.java
  back/src/main/java/org/pknu/weather/dto/WeatherApiResponse.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/test/java/org/pknu/weather/controller/MemberControllerV1Test.java
Labels: :lady_beetle: 버그, :recycle: 리팩토링

#269 [BE/Refactor] 토큰 체크 필터의 로그 레벨 변경
  back/src/main/java/org/pknu/weather/filter/TokenCheckFilter.java
Labels: 백엔드, :recycle: 리팩토링

#271 [BE/Refactor] 약관동의 로직 분리
  back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
  back/src/test/java/org/pknu/weather/controller/MemberControllerV1Test.java
Labels: :recycle: 리팩토링

#278 [BE/Fix]: 회원정보 수정 API에서 이미지 파일이 없을 시 nullexception이 일어나지 않도록 수정
  back/src/main/java/org/pknu/weather/filter/TokenCheckFilter.java
  back/src/main/java/org/pknu/weather/service/MemberService.java
Labels: :lady_beetle: 버그, 백엔드

#280 [BE/Fix] 필터 추가, health 체크용 컨트롤러 추가
  back/src/main/java/org/pknu/weather/config/FilterConfig.java
  back/src/main/java/org/pknu/weather/controller/HealthCheckController.java
  back/src/main/java/org/pknu/weather/filter/InitFilter.java
Labels: 백엔드

#281 [BE/Fix] 추가 수정
  .github/workflows/gradle.yml
  back/src/main/java/org/pknu/weather/config/FilterConfig.java
Labels: 백엔드

#287 [BE/Ci] 개발 서버 ci/cd 워크플로 파일 수정
  .github/workflows/gradle-dev.yml
Labels: CI/CD

#291 [BE/Ci] ci/cd 워크플로 수정
  .github/workflows/gradle-dev.yml
Labels: CI/CD

#294 [BE/Ci] ci/cd 워크플로 수정
  .github/workflows/gradle-dev.yml
  .github/workflows/gradle.yml
Labels: CI/CD
