Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2025-05, with the labels that each got.

#411 [BE/Refactor] 경험치 증가 로직 이벤트 방식으로 변경
  back/src/main/java/org/pknu/weather/config/AsyncConfig.java
  back/src/main/java/org/pknu/weather/event/AbstractExpEvent.java
  back/src/main/java/org/pknu/weather/event/AttendanceCheckedEvent.java
  back/src/main/java/org/pknu/weather/event/ExpRewardListener.java
  back/src/main/java/org/pknu/weather/event/PostCreatedEvent.java
  back/src/main/java/org/pknu/weather/event/RecommendEvent.java
  back/src/main/java/org/pknu/weather/event/RecommendedEvent.java
  back/src/main/java/org/pknu/weather/service/AttendanceService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/java/org/pknu/weather/service/RecommendationService.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
  back/src/test/java/org/pknu/weather/controller/CommunityControllerV1Test.java
  back/src/test/java/org/pknu/weather/service/PostServiceUnitTest.java
Labels: :recycle: 리팩토링

#412 [BE/Feat] 날씨 요약 알림 전송 기능 구현
  .github/pull_request_template.md
  .github/workflows/gradle-dev-ci.yml
  .github/workflows/gradle-prod-ci.yml
  back/build.gradle
  back/src/main/java/org/pknu/weather/WeatherApplication.java
  back/src/main/java/org/pknu/weather/config/FirebaseConfig.java
  back/src/main/java/org/pknu/weather/config/TimeConfig.java
  back/src/main/java/org/pknu/weather/domain/Alarm.java
  back/src/main/java/org/pknu/weather/domain/ExtraWeather.java
  back/src/main/java/org/pknu/weather/domain/common/SummaryAlarmTime.java
  back/src/main/java/org/pknu/weather/dto/AlarmMemberDTO.java
  back/src/main/java/org/pknu/weather/dto/ExtraWeatherSummaryDTO.java
  back/src/main/java/org/pknu/weather/dto/WeatherSummaryDTO.java
  back/src/main/java/org/pknu/weather/dto/converter/ExtraWeatherConverter.java
  back/src/main/java/org/pknu/weather/feignClient/AppleAuthClient.java
  back/src/main/java/org/pknu/weather/repository/AlarmRepository.java
  back/src/main/java/org/pknu/weather/repository/ExtraWeatherRepository.java
  back/src/main/java/org/pknu/weather/repository/LocationRepository.java
  back/src/main/java/org/pknu/weather/repository/MemberCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/MemberCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/MemberRepository.java
  back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/AlarmService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/java/org/pknu/weather/service/dto/AlarmInfo.java
  back/src/main/java/org/pknu/weather/service/dto/WeatherSummaryAlarmInfo.java
  back/src/main/java/org/pknu/weather/service/handler/AlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/AlarmHandlerFactory.java
  back/src/main/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/WeatherUpdateHandler.java
  back/src/main/java/org/pknu/weather/service/message/AlarmMessageMaker.java
  back/src/main/java/org/pknu/weather/service/message/WeatherAlarmMessageBuilder.java
  back/src/main/java/org/pknu/weather/service/message/WeatherSummaryMessageMaker.java
  back/src/main/java/org/pknu/weather/service/sender/FcmMessage.java
  back/src/main/java/org/pknu/weather/service/sender/FcmNotificationSender.java
  back/src/main/java/org/pknu/weather/service/sender/NotificationMessage.java
  back/src/main/java/org/pknu/weather/service/sender/NotificationSender.java
  back/src/main/java/org/pknu/weather/service/supports/AlarmScheduler.java
  back/src/main/java/org/pknu/weather/service/supports/AlarmTimeUtil.java
  back/src/main/java/org/pknu/weather/service/supports/AlarmType.java
  back/src/main/java/org/pknu/weather/service/supports/WeatherRefresherService.java
  back/src/main/resources/application-prod.yml
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/config/DataJpaTestConfig.java
  back/src/test/java/org/pknu/weather/repository/ExtraWeatherRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/MemberCustomRepositoryImplTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/AlarmServiceIntegrationTest.java
  back/src/test/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandlerTest.java
  back/src/test/java/org/pknu/weather/service/message/WeatherAlarmMessageBuilderTest.java
  back/src/test/java/org/pknu/weather/service/message/WeatherSummaryMessageMakerTest.java
  back/src/test/java/org/pknu/weather/service/supports/AlarmHandlerFactoryTest.java
  back/src/test/resources/application.yml
Labels: 백엔드, 기능

#413 [BE/fix]: CI 설정 오타 수정
  .github/workflows/gradle-dev-ci.yml
Labels: :lady_beetle: 버그, 백엔드

#415 [BE/Feat] 알림 전송 및 테스트를 위한 기능 구현
  back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
  back/src/main/java/org/pknu/weather/controller/AlarmControllerV2.java
  back/src/main/java/org/pknu/weather/domain/Alarm.java
  back/src/main/java/org/pknu/weather/domain/common/AlarmType.java
  back/src/main/java/org/pknu/weather/dto/AlarmRequestDTO.java
  back/src/main/java/org/pknu/weather/dto/AlarmResponseDTO.java
  back/src/main/java/org/pknu/weather/dto/converter/AlarmConverter.java
  back/src/main/java/org/pknu/weather/exception/ExceptionAdvice.java
  back/src/main/java/org/pknu/weather/repository/AlarmRepository.java
  back/src/main/java/org/pknu/weather/service/AlarmService.java
  back/src/main/java/org/pknu/weather/service/handler/AlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/AlarmHandlerFactory.java
  back/src/main/java/org/pknu/weather/service/handler/ArgsAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/NoArgsAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/TestWeatherSummaryAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/WeatherUpdateHandler.java
  back/src/main/java/org/pknu/weather/service/message/WeatherSummaryMessageMaker.java
  back/src/main/java/org/pknu/weather/service/supports/AlarmScheduler.java
  back/src/main/java/org/pknu/weather/service/supports/AlarmType.java
  back/src/test/java/org/pknu/weather/integration/AlarmCrudTest.java
  back/src/test/java/org/pknu/weather/integration/AlarmSendTest.java
  back/src/test/java/org/pknu/weather/repository/AlarmRepositoryTest.java
  back/src/test/java/org/pknu/weather/repository/WeatherCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/AlarmServiceTest.java
  back/src/test/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandlerTest.java
  back/src/test/java/org/pknu/weather/service/message/WeatherAlarmMessageBuilderTest.java
  back/src/test/java/org/pknu/weather/service/message/WeatherSummaryMessageMakerTest.java
  back/src/test/java/org/pknu/weather/service/supports/AlarmHandlerFactoryTest.java
Labels: 백엔드, 기능, :recycle: 리팩토링

#416 [BE/Fix]: 한 기기에서 여러 명이 로그인 할 경우를 고려해 수정
  back/src/main/java/org/pknu/weather/controller/AlarmControllerV2.java
  back/src/main/java/org/pknu/weather/domain/Alarm.java
  back/src/main/java/org/pknu/weather/domain/common/AlarmType.java
  back/src/main/java/org/pknu/weather/repository/AlarmRepository.java
  back/src/main/java/org/pknu/weather/service/AlarmService.java
  back/src/main/java/org/pknu/weather/service/handler/TestWeatherSummaryAlarmHandler.java
  back/src/test/java/org/pknu/weather/integration/AlarmCrudTest.java
  back/src/test/java/org/pknu/weather/integration/AlarmSendTest.java
  back/src/test/java/org/pknu/weather/service/AlarmServiceTest.java
Labels: :lady_beetle: 버그, 백엔드
