Repository NeighborhoodWeatherCommunityApp/weather, pull requests merged in 2025-06, with the labels that each got.

#418 [BE/Refactor] 동시에 요청이 발생했을 때 날씨 데이터 생성/갱신 과정에서 데드락이 발생하던 현상 해결 및 리팩토링
  back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
  back/src/main/java/org/pknu/weather/domain/Location.java
  back/src/main/java/org/pknu/weather/domain/Member.java
  back/src/main/java/org/pknu/weather/domain/MemberTerms.java
  back/src/main/java/org/pknu/weather/domain/Post.java
  back/src/main/java/org/pknu/weather/domain/Recommendation.java
  back/src/main/java/org/pknu/weather/domain/Tag.java
  back/src/main/java/org/pknu/weather/domain/Terms.java
  back/src/main/java/org/pknu/weather/domain/Weather.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/domain/WeatherTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
  back/src/test/resources/application.yml
Labels: :recycle: 리팩토링

#420 Feat#419
  .github/workflows/gradle-dev-ci.yml
  back/build.gradle
  back/src/main/java/org/pknu/weather/config/AsyncConfig.java
  back/src/main/java/org/pknu/weather/controller/AlarmControllerV2.java
  back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
  back/src/main/java/org/pknu/weather/domain/common/AlarmType.java
  back/src/main/java/org/pknu/weather/event/alarm/AlarmEventListener.java
  back/src/main/java/org/pknu/weather/event/alarm/AlarmTriggerEvent.java
  back/src/main/java/org/pknu/weather/event/alarm/LiveRainAlarmCreatedEvent.java
  back/src/main/java/org/pknu/weather/repository/AlarmRepository.java
  back/src/main/java/org/pknu/weather/service/AlarmCooldownService.java
  back/src/main/java/org/pknu/weather/service/AlarmService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/java/org/pknu/weather/service/WeatherRefresherService.java
  back/src/main/java/org/pknu/weather/service/dto/LiveRainAlarmInfo.java
  back/src/main/java/org/pknu/weather/service/dto/WeatherSummaryAlarmInfo.java
  back/src/main/java/org/pknu/weather/service/handler/AlarmHandlerFactory.java
  back/src/main/java/org/pknu/weather/service/handler/LiveRainAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/TestWeatherSummaryAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandler.java
  back/src/main/java/org/pknu/weather/service/handler/WeatherUpdateHandler.java
  back/src/main/java/org/pknu/weather/service/message/LiveRainAlarmMessageMaker.java
  back/src/main/resources/application.yml
  back/src/test/java/org/pknu/weather/config/EmbeddedRedisConfig.java
  back/src/test/java/org/pknu/weather/controller/CommunityControllerV1Test.java
  back/src/test/java/org/pknu/weather/integration/AlarmSendTest.java
  back/src/test/java/org/pknu/weather/integration/LiveRainAlarmSendTest.java
  back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceTest.java
  back/src/test/java/org/pknu/weather/service/handler/LiveRainAlarmHandlerTest.java
  back/src/test/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandlerTest.java
  back/src/test/java/org/pknu/weather/service/message/LiveRainAlarmMessageMakerTest.java
  back/src/test/java/org/pknu/weather/service/message/WeatherSummaryMessageMakerTest.java
  back/src/test/resources/application.yml
Labels: 백엔드, 기능

#422 [BE/Refactor] 태그 조회 API 호출 시 예보 데이터가 없는 경우 예외를 반환하던 현상을 해결합니다.
  back/src/main/java/org/pknu/weather/common/mapper/EnumTagMapper.java
  back/src/main/java/org/pknu/weather/controller/TagControllerV1.java
  back/src/main/java/org/pknu/weather/dto/TagWithSelectedStatusDto.java
  back/src/main/java/org/pknu/weather/dto/converter/TagResponseConverter.java
  back/src/main/java/org/pknu/weather/event/exp/AbstractExpEvent.java
  back/src/main/java/org/pknu/weather/event/exp/AttendanceCheckedEvent.java
  back/src/main/java/org/pknu/weather/event/exp/ExpRewardListener.java
  back/src/main/java/org/pknu/weather/event/exp/PostCreatedEvent.java
  back/src/main/java/org/pknu/weather/event/exp/RecommendEvent.java
  back/src/main/java/org/pknu/weather/event/exp/RecommendedEvent.java
  back/src/main/java/org/pknu/weather/event/weather/WeatherCreateEvent.java
  back/src/main/java/org/pknu/weather/event/weather/WeatherRefreshListener.java
  back/src/main/java/org/pknu/weather/event/weather/WeatherUpdateEvent.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
  back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
  back/src/main/java/org/pknu/weather/service/AttendanceService.java
  back/src/main/java/org/pknu/weather/service/MainPageService.java
  back/src/main/java/org/pknu/weather/service/PostService.java
  back/src/main/java/org/pknu/weather/service/RecommendationService.java
  back/src/main/java/org/pknu/weather/service/TagQueryService.java
  back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
  back/src/main/java/org/pknu/weather/service/WeatherService.java
  back/src/test/java/org/pknu/weather/common/TestDataCreator.java
  back/src/test/java/org/pknu/weather/repository/WeatherCustomRepositoryTest.java
  back/src/test/java/org/pknu/weather/service/PostServiceUnitTest.java
  back/src/test/java/org/pknu/weather/service/TagQueryServiceTest.java
  back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java
Labels: :lady_beetle: 버그, :recycle: 리팩토링

#427 [BE/Fix] 날씨요약 알람 에러 수정
  back/src/main/java/org/pknu/weather/repository/ExtraWeatherRepository.java
  back/src/main/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandler.java
  back/src/test/java/org/pknu/weather/service/handler/WeatherSummaryAlarmHandlerTest.java
Labels: :lady_beetle: 버그, 백엔드

#429 [BE/Fix] 알람 전송 형식 수정 및 알람 배지 삭제
  back/src/main/java/org/pknu/weather/service/message/WeatherAlarmMessageBuilder.java
  back/src/main/java/org/pknu/weather/service/sender/FcmNotificationSender.java
  back/src/test/java/org/pknu/weather/service/message/WeatherAlarmMessageBuilderTest.java
Labels: 백엔드, 수정
